export type VisualStyle =
  | 'default'
  | 'neon'
  | 'retro'
  | 'noir'
  | 'vaporwave'
  | 'nature'
  | 'cyberpunk'
  | 'pastel'
  | 'fire'
  | 'ocean'
  | 'sketch'
  | 'dreamscape'
  | 'thermal'
  | 'glitch'
  | 'underwater'
  | 'xray'
  | 'oilPainting'
  | 'pixelate'
  | 'negative'
  | 'astral'
  | 'tiltShift'
  | 'vhs'
  | 'ascii'
  | 'halftone'
  | 'infrared'
  | 'echo'

export type VisualEffectType =
  | 'none'
  | 'edgeDetection'
  | 'dreamscape'
  | 'thermal'
  | 'glitch'
  | 'underwater'
  | 'xray'
  | 'oilPainting'
  | 'pixelate'
  | 'negative'
  | 'astral'
  | 'tiltShift'
  | 'vhs'
  | 'ascii'
  | 'halftone'
  | 'infrared'
  | 'echo'

export interface VisualStyleConfig {
  name: string
  backgroundColor: string
  fogColor: string
  fogNear: number
  fogFar: number
  groundColor: string
  ambientIntensity: number
  ambientColor: string
  directionalIntensity: number
  directionalColor: string
  obstacleColors: string[]
  playerColor: string
  saturation: number
  contrast: number
  brightness: number
  // Post-processing effect
  effectType?: VisualEffectType
  // Edge detection settings
  edgeColor?: string
  edgeThreshold?: number
}

export const visualStyleConfigs: Record<VisualStyle, VisualStyleConfig> = {
  default: {
    name: 'Default',
    backgroundColor: '#1a1a2e',
    fogColor: '#1a1a2e',
    fogNear: 20,
    fogFar: 50,
    groundColor: '#3a5a3a',
    ambientIntensity: 0.4,
    ambientColor: '#ffffff',
    directionalIntensity: 1,
    directionalColor: '#ffffff',
    obstacleColors: ['#ff4444', '#44ff44', '#4444ff', '#ffff44', '#ff44ff', '#44ffff'],
    playerColor: '#4488ff',
    saturation: 1,
    contrast: 1,
    brightness: 1,
  },
  neon: {
    name: 'Neon Glow',
    backgroundColor: '#0a0a0a',
    fogColor: '#0a0a0a',
    fogNear: 15,
    fogFar: 40,
    groundColor: '#1a0a2e',
    ambientIntensity: 0.2,
    ambientColor: '#ff00ff',
    directionalIntensity: 0.8,
    directionalColor: '#00ffff',
    obstacleColors: ['#ff00ff', '#00ffff', '#ff0080', '#80ff00', '#0080ff', '#ffff00'],
    playerColor: '#00ff88',
    saturation: 1.5,
    contrast: 1.3,
    brightness: 1.1,
  },
  retro: {
    name: 'Retro 8-bit',
    backgroundColor: '#2d1b69',
    fogColor: '#2d1b69',
    fogNear: 25,
    fogFar: 60,
    groundColor: '#4a3298',
    ambientIntensity: 0.6,
    ambientColor: '#ffcc00',
    directionalIntensity: 0.7,
    directionalColor: '#ff8800',
    obstacleColors: ['#ff0000', '#00ff00', '#0000ff', '#ffff00', '#ff00ff', '#00ffff'],
    playerColor: '#ffcc00',
    saturation: 1.2,
    contrast: 1.4,
    brightness: 1.0,
  },
  noir: {
    name: 'Film Noir',
    backgroundColor: '#0f0f0f',
    fogColor: '#1a1a1a',
    fogNear: 10,
    fogFar: 35,
    groundColor: '#2a2a2a',
    ambientIntensity: 0.3,
    ambientColor: '#888888',
    directionalIntensity: 1.2,
    directionalColor: '#ffffff',
    obstacleColors: ['#ffffff', '#cccccc', '#999999', '#666666', '#aaaaaa', '#dddddd'],
    playerColor: '#ffffff',
    saturation: 0,
    contrast: 1.5,
    brightness: 0.9,
  },
  vaporwave: {
    name: 'Vaporwave',
    backgroundColor: '#1a0033',
    fogColor: '#2a0044',
    fogNear: 18,
    fogFar: 45,
    groundColor: '#330066',
    ambientIntensity: 0.5,
    ambientColor: '#ff71ce',
    directionalIntensity: 0.9,
    directionalColor: '#01cdfe',
    obstacleColors: ['#ff71ce', '#01cdfe', '#05ffa1', '#b967ff', '#fffb96', '#ff6b6b'],
    playerColor: '#05ffa1',
    saturation: 1.3,
    contrast: 1.1,
    brightness: 1.05,
  },
  nature: {
    name: 'Nature',
    backgroundColor: '#87ceeb',
    fogColor: '#a8d8ea',
    fogNear: 30,
    fogFar: 70,
    groundColor: '#228b22',
    ambientIntensity: 0.6,
    ambientColor: '#fffacd',
    directionalIntensity: 1.1,
    directionalColor: '#fff8dc',
    obstacleColors: ['#8b4513', '#228b22', '#32cd32', '#daa520', '#cd853f', '#6b8e23'],
    playerColor: '#4169e1',
    saturation: 1.1,
    contrast: 1.0,
    brightness: 1.1,
  },
  cyberpunk: {
    name: 'Cyberpunk',
    backgroundColor: '#0d0221',
    fogColor: '#1a0533',
    fogNear: 12,
    fogFar: 40,
    groundColor: '#1a0533',
    ambientIntensity: 0.3,
    ambientColor: '#ff2a6d',
    directionalIntensity: 1.0,
    directionalColor: '#05d9e8',
    obstacleColors: ['#ff2a6d', '#05d9e8', '#d1f7ff', '#ff6b6b', '#01012b', '#ff9f1c'],
    playerColor: '#05d9e8',
    saturation: 1.4,
    contrast: 1.3,
    brightness: 0.95,
  },
  pastel: {
    name: 'Pastel Dream',
    backgroundColor: '#ffeef8',
    fogColor: '#fff0f5',
    fogNear: 25,
    fogFar: 55,
    groundColor: '#e8f5e9',
    ambientIntensity: 0.7,
    ambientColor: '#ffffff',
    directionalIntensity: 0.8,
    directionalColor: '#fffaf0',
    obstacleColors: ['#ffb3ba', '#baffc9', '#bae1ff', '#ffffba', '#ffdfba', '#e0bbff'],
    playerColor: '#a8d8ea',
    saturation: 0.7,
    contrast: 0.9,
    brightness: 1.15,
  },
  fire: {
    name: 'Inferno',
    backgroundColor: '#1a0000',
    fogColor: '#2a0a00',
    fogNear: 15,
    fogFar: 40,
    groundColor: '#330000',
    ambientIntensity: 0.4,
    ambientColor: '#ff4400',
    directionalIntensity: 1.0,
    directionalColor: '#ffaa00',
    obstacleColors: ['#ff0000', '#ff4400', '#ff8800', '#ffcc00', '#ff2200', '#ff6600'],
    playerColor: '#ffff00',
    saturation: 1.3,
    contrast: 1.2,
    brightness: 1.0,
  },
  ocean: {
    name: 'Deep Ocean',
    backgroundColor: '#001133',
    fogColor: '#002244',
    fogNear: 12,
    fogFar: 38,
    groundColor: '#003355',
    ambientIntensity: 0.4,
    ambientColor: '#00aaff',
    directionalIntensity: 0.8,
    directionalColor: '#88ddff',
    obstacleColors: ['#00ffff', '#0088ff', '#00ff88', '#44aaff', '#00ccaa', '#66ddff'],
    playerColor: '#ffff88',
    saturation: 1.1,
    contrast: 1.1,
    brightness: 0.95,
  },
  sketch: {
    name: 'Sketch',
    backgroundColor: '#f5f5f0',
    fogColor: '#f5f5f0',
    fogNear: 30,
    fogFar: 80,
    groundColor: '#e8e8e0',
    ambientIntensity: 0.8,
    ambientColor: '#ffffff',
    directionalIntensity: 0.6,
    directionalColor: '#ffffff',
    obstacleColors: ['#d0d0c8', '#c8c8c0', '#e0e0d8', '#d8d8d0', '#c0c0b8', '#e8e8e0'],
    playerColor: '#a0a098',
    saturation: 0.1,
    contrast: 0.8,
    brightness: 1.1,
    effectType: 'edgeDetection',
    edgeColor: '#1a1a1a',
    edgeThreshold: 0.08,
  },
  dreamscape: {
    name: 'Dreamscape',
    backgroundColor: '#1a1a2e',
    fogColor: '#2a2040',
    fogNear: 15,
    fogFar: 50,
    groundColor: '#3a3a5a',
    ambientIntensity: 0.5,
    ambientColor: '#9988ff',
    directionalIntensity: 0.7,
    directionalColor: '#ffaadd',
    obstacleColors: ['#8866cc', '#66aacc', '#aa66aa', '#6688bb', '#9977bb', '#7799aa'],
    playerColor: '#aaccff',
    saturation: 1.2,
    contrast: 0.9,
    brightness: 1.0,
    effectType: 'dreamscape',
  },
  thermal: {
    name: 'Thermal Vision',
    backgroundColor: '#0a0a15',
    fogColor: '#0a0a15',
    fogNear: 20,
    fogFar: 60,
    groundColor: '#1a1a2a',
    ambientIntensity: 0.6,
    ambientColor: '#ffffff',
    directionalIntensity: 0.8,
    directionalColor: '#ffffff',
    obstacleColors: ['#444466', '#555577', '#333355', '#445566', '#334455', '#556677'],
    playerColor: '#ffffff',
    saturation: 1.0,
    contrast: 1.1,
    brightness: 1.0,
    effectType: 'thermal',
  },
  glitch: {
    name: 'Glitch',
    backgroundColor: '#0a0a0a',
    fogColor: '#0a0a0a',
    fogNear: 15,
    fogFar: 45,
    groundColor: '#1a1a1a',
    ambientIntensity: 0.4,
    ambientColor: '#ffffff',
    directionalIntensity: 0.9,
    directionalColor: '#ffffff',
    obstacleColors: ['#ff0040', '#00ff40', '#0040ff', '#ff00ff', '#00ffff', '#ffff00'],
    playerColor: '#ffffff',
    saturation: 1.3,
    contrast: 1.2,
    brightness: 1.0,
    effectType: 'glitch',
  },
  underwater: {
    name: 'Underwater',
    backgroundColor: '#001a33',
    fogColor: '#003355',
    fogNear: 8,
    fogFar: 35,
    groundColor: '#002244',
    ambientIntensity: 0.4,
    ambientColor: '#4488aa',
    directionalIntensity: 0.6,
    directionalColor: '#88ccff',
    obstacleColors: ['#225566', '#336677', '#447788', '#224455', '#335566', '#446677'],
    playerColor: '#88aacc',
    saturation: 0.8,
    contrast: 0.9,
    brightness: 0.9,
    effectType: 'underwater',
  },
  xray: {
    name: 'X-Ray',
    backgroundColor: '#000508',
    fogColor: '#001020',
    fogNear: 20,
    fogFar: 70,
    groundColor: '#001015',
    ambientIntensity: 0.3,
    ambientColor: '#00ffff',
    directionalIntensity: 0.5,
    directionalColor: '#00aaff',
    obstacleColors: ['#003344', '#004455', '#002233', '#005566', '#003355', '#004466'],
    playerColor: '#00ddff',
    saturation: 0.5,
    contrast: 1.3,
    brightness: 1.0,
    effectType: 'xray',
  },
  oilPainting: {
    name: 'Oil Painting',
    backgroundColor: '#2a2a1a',
    fogColor: '#3a3a2a',
    fogNear: 25,
    fogFar: 60,
    groundColor: '#4a5a3a',
    ambientIntensity: 0.6,
    ambientColor: '#ffffee',
    directionalIntensity: 0.9,
    directionalColor: '#ffeecc',
    obstacleColors: ['#8b4513', '#228b22', '#4169e1', '#daa520', '#8b008b', '#2f4f4f'],
    playerColor: '#cd853f',
    saturation: 1.4,
    contrast: 1.1,
    brightness: 1.0,
    effectType: 'oilPainting',
  },
  pixelate: {
    name: 'Pixelate',
    backgroundColor: '#1a1a2e',
    fogColor: '#1a1a2e',
    fogNear: 20,
    fogFar: 50,
    groundColor: '#2d5a27',
    ambientIntensity: 0.5,
    ambientColor: '#ffffff',
    directionalIntensity: 0.8,
    directionalColor: '#ffffff',
    obstacleColors: ['#ff0000', '#00ff00', '#0000ff', '#ffff00', '#ff00ff', '#00ffff'],
    playerColor: '#4488ff',
    saturation: 1.5,
    contrast: 1.3,
    brightness: 1.1,
    effectType: 'pixelate',
  },
  negative: {
    name: 'Negative',
    backgroundColor: '#f0f0f0',
    fogColor: '#e0e0e0',
    fogNear: 15,
    fogFar: 50,
    groundColor: '#c0c0b0',
    ambientIntensity: 0.7,
    ambientColor: '#ffffff',
    directionalIntensity: 0.8,
    directionalColor: '#ffffff',
    obstacleColors: ['#cccccc', '#bbbbbb', '#dddddd', '#aaaaaa', '#eeeeee', '#999999'],
    playerColor: '#888888',
    saturation: 1.0,
    contrast: 1.0,
    brightness: 1.0,
    effectType: 'negative',
  },
  astral: {
    name: 'Astral',
    backgroundColor: '#0a0015',
    fogColor: '#150025',
    fogNear: 15,
    fogFar: 50,
    groundColor: '#1a0a2a',
    ambientIntensity: 0.4,
    ambientColor: '#aa88ff',
    directionalIntensity: 0.6,
    directionalColor: '#ffaaff',
    obstacleColors: ['#6644aa', '#8866cc', '#aa88ee', '#5533aa', '#7755cc', '#9977ee'],
    playerColor: '#ccaaff',
    saturation: 1.2,
    contrast: 1.0,
    brightness: 1.05,
    effectType: 'astral',
  },
  tiltShift: {
    name: 'Tilt Shift',
    backgroundColor: '#87ceeb',
    fogColor: '#a8d8ea',
    fogNear: 40,
    fogFar: 100,
    groundColor: '#228b22',
    ambientIntensity: 0.7,
    ambientColor: '#fffacd',
    directionalIntensity: 1.2,
    directionalColor: '#fff8dc',
    obstacleColors: ['#8b4513', '#228b22', '#32cd32', '#daa520', '#cd853f', '#6b8e23'],
    playerColor: '#4169e1',
    saturation: 1.4,
    contrast: 1.2,
    brightness: 1.15,
    effectType: 'tiltShift',
  },
  vhs: {
    name: 'VHS',
    backgroundColor: '#0a0a0a',
    fogColor: '#1a1a1a',
    fogNear: 15,
    fogFar: 45,
    groundColor: '#2a2a2a',
    ambientIntensity: 0.5,
    ambientColor: '#ffffff',
    directionalIntensity: 0.7,
    directionalColor: '#ffffff',
    obstacleColors: ['#cc4444', '#44cc44', '#4444cc', '#cccc44', '#cc44cc', '#44cccc'],
    playerColor: '#ffffff',
    saturation: 0.9,
    contrast: 1.2,
    brightness: 0.95,
    effectType: 'vhs',
  },
  ascii: {
    name: 'ASCII',
    backgroundColor: '#000000',
    fogColor: '#000000',
    fogNear: 30,
    fogFar: 80,
    groundColor: '#001100',
    ambientIntensity: 0.8,
    ambientColor: '#00ff00',
    directionalIntensity: 0.6,
    directionalColor: '#00ff00',
    obstacleColors: ['#00aa00', '#00cc00', '#008800', '#00bb00', '#009900', '#00dd00'],
    playerColor: '#00ff00',
    saturation: 0.5,
    contrast: 1.5,
    brightness: 1.1,
    effectType: 'ascii',
  },
  halftone: {
    name: 'Halftone',
    backgroundColor: '#ffffff',
    fogColor: '#f0f0f0',
    fogNear: 25,
    fogFar: 60,
    groundColor: '#e0e0e0',
    ambientIntensity: 0.7,
    ambientColor: '#ffffff',
    directionalIntensity: 0.8,
    directionalColor: '#ffffff',
    obstacleColors: ['#ff0000', '#0000ff', '#ffff00', '#00ffff', '#ff00ff', '#000000'],
    playerColor: '#000000',
    saturation: 1.5,
    contrast: 1.3,
    brightness: 1.1,
    effectType: 'halftone',
  },
  infrared: {
    name: 'Infrared',
    backgroundColor: '#1a0a0a',
    fogColor: '#2a1515',
    fogNear: 15,
    fogFar: 50,
    groundColor: '#ff8866',
    ambientIntensity: 0.5,
    ambientColor: '#ffaa88',
    directionalIntensity: 0.8,
    directionalColor: '#ff6644',
    obstacleColors: ['#ff4488', '#ff88aa', '#ff6688', '#ffaacc', '#ff8888', '#ffccaa'],
    playerColor: '#ffffff',
    saturation: 1.2,
    contrast: 1.1,
    brightness: 1.0,
    effectType: 'infrared',
  },
  echo: {
    name: 'Echo',
    backgroundColor: '#0a0a1a',
    fogColor: '#151530',
    fogNear: 15,
    fogFar: 50,
    groundColor: '#1a1a3a',
    ambientIntensity: 0.4,
    ambientColor: '#8888ff',
    directionalIntensity: 0.6,
    directionalColor: '#aaaaff',
    obstacleColors: ['#6666aa', '#7777bb', '#5555aa', '#8888cc', '#6677aa', '#7788bb'],
    playerColor: '#aabbff',
    saturation: 1.1,
    contrast: 1.0,
    brightness: 1.0,
    effectType: 'echo',
  },
}

export const visualStyleOptions: VisualStyle[] = [
  'default',
  'neon',
  'retro',
  'noir',
  'vaporwave',
  'nature',
  'cyberpunk',
  'pastel',
  'fire',
  'ocean',
  'sketch',
  'dreamscape',
  'thermal',
  'glitch',
  'underwater',
  'xray',
  'oilPainting',
  'pixelate',
  'negative',
  'astral',
  'tiltShift',
  'vhs',
  'ascii',
  'halftone',
  'infrared',
  'echo',
]
