// Individual effects
export { EdgeDetectionEffect } from './EdgeDetectionEffect'
export type { EdgeDetectionEffectOptions } from './EdgeDetectionEffect'
export { DreamscapeEffect } from './DreamscapeEffect'
export { ThermalEffect } from './ThermalEffect'
export { GlitchEffect } from './GlitchEffect'
export { UnderwaterEffect } from './UnderwaterEffect'
export { XrayEffect } from './XrayEffect'
export { OilPaintingEffect } from './OilPaintingEffect'
export { PixelateEffect } from './PixelateEffect'
export { NegativeEffect } from './NegativeEffect'
export { AstralEffect } from './AstralEffect'
export { TiltShiftEffect } from './TiltShiftEffect'
export { VhsEffect } from './VhsEffect'
export { AsciiEffect } from './AsciiEffect'
export { HalftoneEffect } from './HalftoneEffect'
export { InfraredEffect } from './InfraredEffect'
export { EchoEffect } from './EchoEffect'

// Registry and params
export { effectRegistry, createEffect } from './effectRegistry'
export { effectParams, getEffectParams, getEffectDefaults } from './effectParams'
export type { EffectParam } from './effectParams'
